# Generated by Django 5.1.7 on 2025-03-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Данное поле заполняется автоматически', verbose_name='Слаг')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='products/preview/', verbose_name='Заставка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Полное описание')),
                ('barcode', models.CharField(max_length=100, verbose_name='Штрих код')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии?')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
