# Generated by Django 5.1.7 on 2025-03-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='slug',
            field=models.SlugField(help_text='Данное поле заполнять не нужно', verbose_name='Короткая ссылка на продукт'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(help_text='Данное поле заполнять не нужно!', max_length=150, verbose_name='Короткая ссылка'),
        ),
    ]
