# Generated by Django 5.1.7 on 2025-03-31 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_productvariant_slug_alter_subcategory_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
