# Generated by Django 5.1.7 on 2025-04-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_categoryage_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pages',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество страниц'),
        ),
    ]
