# Generated by Django 5.1.7 on 2025-04-11 10:29

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_product_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.product_image_gallery_path, verbose_name='Фотография'),
        ),
    ]
