# Generated by Django 5.1.7 on 2025-04-12 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_product_main_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.publishinghouse', verbose_name='Издательство'),
        ),
    ]
