# Generated by Django 5.1.7 on 2025-07-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='preview',
            field=models.ImageField(blank=True, default='placeholder.jpg', null=True, upload_to='news/', verbose_name='фото'),
        ),
    ]
