# Generated by Django 5.1.7 on 2025-04-07 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_publishinghouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='Возраст')),
            ],
            options={
                'verbose_name': 'Возраст',
                'verbose_name_plural': 'Возрастa',
            },
        ),
        migrations.CreateModel(
            name='ProductBaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Короткая ссылка')),
            ],
            options={
                'verbose_name': 'Базовая категория',
                'verbose_name_plural': 'Базовые категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.IntegerField(unique=True, verbose_name='Штрихкод')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Короткая ссылка')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Заставка')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('sku', models.CharField(max_length=200, verbose_name='Артикул')),
                ('product_code', models.IntegerField(default=0, verbose_name='Код товара')),
                ('ages', models.ManyToManyField(to='main.categoryage', verbose_name='Возраста')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.category', verbose_name='Основная категория')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.publishinghouse', verbose_name='Издательство')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.subcategory', verbose_name='Подкатегория')),
                ('base_category', models.ManyToManyField(related_name='products', to='main.productbasecategory', verbose_name='Базовые категории')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
