# Generated by Django 5.1.7 on 2025-04-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryage',
            name='age',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Возраст'),
        ),
    ]
