# Generated by Django 5.1.7 on 2025-04-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_product_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Артикул'),
        ),
    ]
