# Generated by Django 5.1.7 on 2025-04-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='binding',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Переплет'),
        ),
    ]
