# Generated by Django 5.1.7 on 2025-06-01 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_product_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_category',
        ),
        migrations.DeleteModel(
            name='ProductBaseCategory',
        ),
    ]
