# Generated by Django 5.1.7 on 2025-06-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
