# Generated by Django 5.1.7 on 2025-06-10 21:00

import core.apps.main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_remove_product_product_code_remove_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=core.apps.main.models.make_preview_image_path, verbose_name='Заставка'),
        ),
    ]
