# Generated by Django 5.1.7 on 2025-06-10 21:03

import core.apps.main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_product_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.apps.main.models.product_image_gallery_path, verbose_name='Фотография'),
        ),
    ]
