# Generated by Django 5.1.7 on 2025-06-10 22:41

import core.apps.main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_product_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preview',
            field=models.ImageField(blank=True, default='placeholder.jpg', null=True, upload_to=core.apps.main.models.make_preview_image_path, verbose_name='Заставка'),
        ),
    ]
