# Generated by Django 5.1.7 on 2025-07-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_product_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='placeholder.jpg', null=True, upload_to='categories/', verbose_name='Фото категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Сделать категорию популярной'),
        ),
    ]
