# Generated by Django 5.1.7 on 2025-07-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_category_image_category_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_on_promotion',
            field=models.BooleanField(default=False, verbose_name='Является товаром по акции?'),
        ),
    ]
