# Generated by Django 5.1.7 on 2025-07-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_product_is_on_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Вес гр'),
        ),
    ]
