# Generated by Django 5.1.7 on 2025-07-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ordering_number',
            field=models.IntegerField(default=0, help_text='Укажите число, под каким номером данная категория должна отображаться', verbose_name='Порядковый номер категории'),
        ),
    ]
